export const ON_AUTOCOMPLETE_SUCCESS = 'ON_AUTOCOMPLETE_SUCCESS';
export const ON_GET_CURRENT_WEATHER_SUCCESS = 'ON_GET_CURRENT_WEATHER_SUCCESS';
export const ON_GET_FIVE_DAY_FORECAST_SUCCESS = 'ON_GET_FIVE_DAY_FORECAST_SUCCESS';
export const ON_REQUEST_FAILED = 'ON_REQUEST_FAILED';

export const ON_ADD_TO_FAVORITES = 'ON_ADD_TO_FAVORITES';
export const ON_REMOVE_FROM_FAVORITES = 'ON_REMOVE_FROM_FAVORITES';

export const CHANGE_CURRENT_LOCATION = 'CHANGE_CURRENT_LOCATION';

export const CLEAR_ERROR = 'CLEAR_ERROR';

export const CHANGE_VIEW = 'CHANGE_VIEW';

